apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.60.0.6
  share: /mnt/sdx-pool-0/sdx-starbase
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
