apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: velero
spec:
  schedule: "0 2 * * *"  # 2 AM daily
  template:
    includedNamespaces:
      - "*"
    excludedNamespaces:
      - velero
      - kube-system
      - kube-public
      - kube-node-lease
    ttl: 720h0m0s  # 30 days in hours
    storageLocation: default
